### ISSUE TITLE
Saving the decoder generated images to separate class-specific folders

### ISSUE THREAD

**Issue by ghost** [chaitanya100100/VAE-for-Image-Generation#3]
With CIFAR-10, I would like to save the decoder generated images to separate class specific folders in the local system so that I could use them as augmented data for further training. Kindly let know how to modify the code in the cifar10_generate.py. Thanks and looking forward.

**Comment by chaitanya100100** [comment]
The encoder learns to output through a continuous manifold. We are not using labels here. That means we are just generating images that belong to the distribution of the digits data, not some particular digit. According to my understanding, you need to train a class-conditional generator for your purpose.
